### ISSUE TITLE
Different behavior when passing strings or symbols as keys to options hash

### ISSUE THREAD

**Issue by rangerscience** [rightsignature/rightsignature-api#22]
`@rs_connection.prepackage_and_send guid, roles, {subject: "Good"}` produces a document with the subject "Good".

`$right_signature_connection.prepackage_and_send guid, roles, {"subject" => "Good"}` produces a document with the subject "["TEMPLATE SUBJECT", "Good"]"

This does not occur for `description`, only `subject`.

**Comment by narfanator** [comment]
This also effects `use_merge_field_ids`. It needs to be a symbol, not a string.

**Comment by rangerscience** [comment]
Pull Request #25 resolves this.

**Comment by rangerscience** [comment]
Ridiculously stale, even if it's still an issue.
